[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "page source code analyzer"
authors = ["sanswed <sanswed@gmail.com>"]
packages = [
  { include = "page_analyzer" },
  ]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
